### ISSUE TITLE
Bug: Participant list and checkboxes don't always align

### ISSUE THREAD

**Issue by wrynearson** [developmentseed/co2ordinate#20]
## Current Behavior
- When a user is `deleted`, their name still exists in the list, and their name is still checked
- When all users are removed from the `multiselect`, their check boxes still are checked, and then become out of sync

https://github.com/developmentseed/meet-and-greta/assets/25919630/ad5aecf4-567f-4a6b-85c4-4b8afff27723

https://github.com/developmentseed/meet-and-greta/assets/25919630/e35c1907-fb5c-4fa8-8a86-d9dabb4bac7c

## Expected Behavior

- [ ] When a user is `deleted`, their name is removed from the `multiselect` and their name is removed from the list
- [ ] When a user is `unchecked`, their name is removed from the `multiselect`

**Comment by wrynearson** [comment]
@nerik sadly this issue still exists. When a group is deselected, their checkbox still remains checked.

https://github.com/developmentseed/co2ordinate/assets/25919630/43ebef49-c0f8-4abc-829c-e06f6a8fa3c7

**Comment by wrynearson** [comment]
☝️ was when running locally. The deployed version seems fine, so I'll close this again. Sorry for the 🏓

**Comment by nerik** [comment]
@wrynearson Can you try [clearing your local storage](https://support.conquer.io/hc/en-us/articles/5821475923988-How-to-clear-local-storage-in-Chrome) and see if that happens again? (or alternatively, try in incognito mode)
