### ISSUE TITLE
Map style

### ISSUE THREAD

**Issue by nerik** [developmentseed/co2ordinate#29]
Replace map style with the style that @LanesGood had in the designs.
- [x] @LanesGood On which MB account is that style hosted?
- [ ] Update markers style/colors

**Comment by LanesGood** [comment]
The map style shown in #24 was on my personal account. I'll export the style and put in our company studio account. May play around with styles a little more

**Comment by LanesGood** [comment]
Map style now in devseed account. [See map preview here](https://api.mapbox.com/styles/v1/devseed/clnapv13800e501qnho9l4foc.html?title=view&access_token=pk.eyJ1IjoiZGV2c2VlZCIsImEiOiJnUi1mbkVvIn0.018aLhX0Mb0tdtaT2QNe2Q&zoomwheel=true&fresh=true#8.38/48.405/1.521)
