### ISSUE TITLE
Map doesn't load

### ISSUE THREAD

**Issue by achou11** [developmentseed/co2ordinate#36]
Attempted to access https://devseed.com/co2ordinate/ using both Firefox and Chromium-based browsers on a desktop (also in private windows), but the actual map never loads for me.

<img width="897" alt="image" src="https://github.com/developmentseed/co2ordinate/assets/18542095/07897558-7c3a-4d7b-a0d5-03e8eb1366bf">

**Comment by willemarcel** [comment]
@achou11 thanks for reporting! It's fixed now.
